mydata = read.csv('map_data.csv')
summary(mydata)
summary(mydata$TrackType)
summary(mydata$LineName)
summary(mydata$Line)
summary(mydata$Track)
summary(mydata$DefectType)
summary(mydata$DefectSize)
summary(mydata$PlateType)
summary(mydata$RailType)
summary(mydata$Manufacturer)
